account/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

from .views import UserRegistrationView, UserObtainTokenPairView

urlpatterns = [
    path('token/', UserObtainTokenPairView.as_view(), name='token_obtain_pair'),
    # path('token/verify', UserTokenVerifyView.as_view(), name='token_verify'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    # path('subscribe/', CreateSubscription.as_view(), name='create_subscription')
]

carrier_data_tool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from account import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/account/', include('account.urls')),
    path('api/company/', include('company.urls')),
    path('', RedirectView.as_view(url='/company/companies/', permanent=True)),
    # path("stripe/", include("djstripe.urls", namespace="djstripe")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

company/urls.py
from django.conf import urls
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
app_name = 'company'
router = DefaultRouter()
router.register('companies', views.CompanyList, basename='company')
urlpatterns = [
    path('add-company/', views.CreateCompany.as_view(), name='add_company'),
    # path('company/<slug:pk>/', views.CompanyDetailView.as_view(), name='company_detail'),
]
urlpatterns += router.urls

company/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
from phonenumber_field.modelfields import PhoneNumberField

from carrier_data_tool.base_models import BaseModel


class CompanyBaseModel(models.Model):
    created_by = models.CharField(max_length=50, null=True)
    modified_by = models.CharField(max_length=50, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Company(CompanyBaseModel):
    name = models.CharField(max_length=255, blank=True, null=True)
    dba = models.CharField(max_length=255, blank=True, null=True)
    legal_name = models.CharField(_('Company legal name'),max_length=255)
    dot = models.IntegerField(unique=True)
    is_active = models.BooleanField(default=True)
    incorporation_date = models.DateField(_('Date of Incorporation'), blank=True, null=True)
    motor_carrier_number = models.PositiveIntegerField(null=True, blank=True, validators=(MaxValueValidator(9999999),))

    ein = models.IntegerField(null=True, blank=True)
    census_type= models.CharField(max_length=20, blank=True, null=True)
    total_driver = models.IntegerField(null=True, blank=True)
    carrier_operation = models.CharField(max_length=50, blank=True, null=True)
    common_authority_status = models.CharField(max_length=5, blank=True, null=True)
    contract_authority_status = models.CharField(max_length=5, blank=True, null=True)
    docket_number = models.CharField(max_length=15, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)


class CompanyAddress(BaseModel):
    class Address_Type_Choice(models.TextChoices):
        BILLING = 'B', _('Billing Adress')
        OFFICE = 'O', _('Office Address')

    address_type = models.CharField(max_length=20 ,choices=Address_Type_Choice.choices, default=Address_Type_Choice.BILLING, blank=True, null=True)
    address_1 = models.CharField(_('Address Line 1'), max_length=1024, blank=True, null=True)
    address_2 = models.CharField(_('Address Line 2'), max_length=1024, blank=True, null=True)
    email = models.EmailField(_('Company mail'), null=True, blank=True)
    city = models.CharField(_('City'), max_length=100)
    street = models.CharField(_('Street'), max_length=100, null=True, blank=True)
    state = models.CharField(_('State'), max_length=50)
    zip_code = models.CharField(_('Zip / Postal Code'), max_length=10)
    country = models.CharField(_('Country'), max_length=100)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='addresses')


class LicensingAndInsurence(models.Model):
    company = models.OneToOneField(Company, related_name='insurance', on_delete=models.CASCADE)
    bipdInsuranceRequired = models.CharField(max_length=5, null=True, blank=True)
    bipdInsuranceOnFile = models.IntegerField(null=True, blank=True)
    bipdRequiredAmount = models.IntegerField(null=True, blank=True)
    bondInsuranceOnFile = models.IntegerField(null=True, blank=True)
    bondInsuranceRequired = models.CharField(max_length=5, null=True, blank=True)


class OperationClasfication(models.Model):
    operaton_classfication_id = models.IntegerField()
    operation_classification_description = models.CharField(max_length=100,blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='operaton_classfication')

class CompanyRepresentative(BaseModel):
    email = models.EmailField(_('Representative mail'), null=True, blank=True)
    address_1 = models.CharField(_('Address Line 1'), max_length=1024, blank=True, null=True)
    address_2 = models.CharField(_('Address Line 2'), max_length=1024, blank=True, null=True)
    city = models.CharField(_('City'), max_length=100)
    state = models.CharField(_('State'), max_length=50)
    zip_code = models.CharField(_('Zip / Postal Code'), max_length=10)
    country = models.CharField(_('Country'), max_length=100)
    phone = PhoneNumberField(_('Phone Number'), blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='representatives')


class Basics(models.Model):
    basics_id = models.IntegerField()
    percentile = models.FloatField(null=True, blank=True)
    run_date = models.DateTimeField(blank=True, null=True)
    violation_threshold = models.FloatField(blank=True,null=True)
    exceeded_fmcsa_intervention_threshold = models.FloatField(blank=True,null=True)
    measure_value = models.FloatField(blank=True, null=True)
    on_road_performance_threshold_violation_indicator = models.CharField(max_length=100, blank=True, null=True)
    serious_violation_investigation_past_12month_Indicator = models.CharField(max_length=100, blank=True, null=True)
    total_inspection_with_violation = models.IntegerField(null=True, blank=True)
    total_violation = models.IntegerField(null=True, blank=True)
    company = models.ForeignKey(Company, related_name='basics', on_delete=models.CASCADE)


class BasicsEntity(models.Model):
    code = models.CharField(max_length=100)
    code_mcmis = models.CharField(max_length=100, null=True, blank=True)
    long_description = models.CharField(max_length=100, blank=True, null=True)
    short_description = models.CharField(max_length=100, blank=True, null=True)
    basics = models.OneToOneField(Basics, on_delete=models.CASCADE, related_name='basics_entity')

class Hazmat(models.TextChoices):
    HAZMAT = 'H', _('HAZMAT')
    NON_HAZMAT = 'N', _('NON_HAZMAT')

class InspectionAndSafetyMeasures(models.Model):

    hazmat = models.CharField(max_length=20, choices=Hazmat.choices, default=Hazmat.HAZMAT)
    inspection_total = models.IntegerField(blank=True, null=True)
    driver_inspection_total = models.IntegerField(blank=True, null=True)
    driver_oos_inspection_total = models.IntegerField(blank=True, null=True)
    vehicle_inspection_total = models.IntegerField(blank=True, null=True)
    vehicle_oos_inspection_total = models.IntegerField(blank=True, null=True)
    unsafe_driver_inspection_violation = models.IntegerField(blank=True, null=True)
    unsafe_driver_measure = models.IntegerField(blank=True, null=True)
    hos_driver_inspection_violation = models.IntegerField(blank=True, null=True)
    hos_driver_measure = models.IntegerField(blank=True, null=True)
    driver_fit_inspection_violation = models.IntegerField(blank=True, null=True)
    driver_fit_measure = models.IntegerField(blank=True, null=True)
    contr_subst_inspection_violation = models.IntegerField(blank=True, null=True)
    contr_subst_measure = models.IntegerField(blank=True, null=True)
    vehicle_maintenance_violation = models.IntegerField(blank=True, null=True)
    vehicle_maintenance_measure = models.IntegerField(blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='inspection_safety')

    class Meta:
        unique_together = ('company', 'hazmat')


class CargoCarried(models.Model):
    cargo_id = models.IntegerField()
    description = models.CharField(max_length=255, blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='cargo')

# class SafetRating(models.Model):
#     safety_rating = models.Ch


class InsuranceHistory(models.Model):
    form = models.CharField(max_length=20)
    type = models.CharField(max_length=50)
    insurance_carrier = models.CharField(max_length=255, blank=True, null=True)
    policy_surety = models.CharField(max_length=100, blank=True, null=True, unique=True)
    coverage_from = models.CharField(max_length=10)
    coverage_to = models.CharField(max_length=10)
    effective_date_from = models.DateField(null=True, blank=True)
    effective_date_to = models.DateField(null=True, blank=True)
    company = models.ForeignKey(Company, related_name='insurance_history', on_delete=models.CASCADE)
    status = models.CharField(max_length=20, null=True, blank=True)

class Crash(models.Model):
    crash_total = models.IntegerField()
    fatal_crash = models.IntegerField()
    injury_crash = models.IntegerField()
    towaway_crash = models.IntegerField()
    company = models.OneToOneField(Company, on_delete=models.CASCADE, related_name='crashes')

company/forms.py
from .models import *
from django import forms

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'legal_name', 'dot', 'is_active', 'incorporation_date', 'motor_carrier_number']

company/templates/company_data_fill.html
{% extends 'base.html' %}
{% load static %}
{% load myfilters %}
{% block content %}
<style>
    .main-area{
    display: flex;
    align-items: center;
    }

    .register-form{
        width:100%;
        max-width: 500px;
        margin:auto;
        margin-top:40px;
        padding:20px;
        background-color: #fff;
        border-top: 5px solid #0D8BF6;
        border-radius: 5px;
    }
    div {
        d-flex justify-content-center
    }

</style>
<form method="POST">{% csrf_token %}
<div class="'main-area">

    <div class="register-form">
        <h2 class="mainheading">Add Company Data</h2>
        <!--          <h4 class="mainheading"></h4>-->
        <p class="errorlist">{{ form.non_field_errors }}</p>
        <label for="id_name" class="login-labels mt-2">Company Name*</label>
        {{ form.name.errors }}
        {{ form.name|addclass:'form-control'|addplaceholder:'Company Name'}}

        <label for="id_legal_name" class="login-labels mt-2">Legal Name*</label>
          {{ form.legal_name.errors }}
          {{ form.legal_name|addclass:'form-control'|addplaceholder:'Legal Name'}}

        <label for="id_dot" class="login-labels mt-2">DOT*</label>
          {{ form.dot.errors }}
          {{ form.dot|addclass:'form-control'|addplaceholder:'DOT'}}

        <label for="id_incorporation_date" class="login-labels mt-2">Incorporation Date</label>
          {{ form.incorporation_date.errors }}
          {{ form.incorporation_date|addclass:'form-control'|addplaceholder:'Incorporation Date'}}

        <label for="id_motor_carrier_number" class="login-labels mt-2">Motor Carrier Number</label>
          {{ form.motor_carrier_number.errors }}
          {{ form.motor_carrier_number|addclass:'form-control'|addplaceholder:'Motor Carrier Number'}}

        <label for="id_is_active" class="login-labels mt-2">Is Active</label>
          {{ form.is_active.errors }}
          {{ form.is_active|addclass:'form-control'|addplaceholder:'Company is active?'}}
        <span class="d-flex justify-content-center">
            <button type="submit"  class="btn btn-primary btn-lg signup-button m-2 ">Add Company</button>
        </span>

    </div>
</div>
{% endblock %}

company/templates/company_detail.html
{% extends 'base.html' %}
{% load static %}
{% load static %}
{% block content %}
<style>

</style>
    {% block title %}
        Company Detail
    {% endblock %}
<div class="'main-area ml-4 mr-4">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Company</th>
          <th scope="col">Legal Name</th>
          <th scope="col">Dot</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <th scope="row"></th>
          <td>{{company_data.name}}</td>
          <td>{{company_data.legal_name}}</td>
          <td>{{company_data.dot}}</td>
        </tr>
      </tbody>
    </table>
</div>
{% endblock %}

company/templates/company_list.html
{% extends 'base.html' %}
{% load static %}
{% load myfilters %}
{% load bootstrap %}}
{% block content %}

<style>
    .main-area{
    display: flex;
    align-items: center;

    }
</style>
    {% block title %}
        Companies
    {% endblock %}
<div class="'main-area ml-4 mr-4">
    <form method="GET">
        {{filter.form | bootstrap}}
        <button type="submit" id='myBtn' class="'btn btn-primary center">Search</button>
    </form>

    <table class="table">
      <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Company</th>
            <th scope="col">Legal Name</th>
            <th scope="col">Dot</th>
            <th scope="col">Address</th>
        </tr>
      </thead>
        <hr>
      <tbody>
      {% for data in company_page_obj %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'company_detail' data.id %}">{{data.name}}</a></td>
            <td>{{data.legal_name}}</td>
            <td>{{data.dot}}</td>
            <td>{{data.addresses.city}}</td>

        </tr>
      {% endfor %}
      </tbody>
    </table>
</div>

    <div class="'pagination d-flex justify-content-center font-weight-bold">
        <span class="step-links">
            {% if company_page_obj.has_previous %}
                <a href="{% my_url 1 'page' request.GET.urlencode %}">&laquo; First</a>
                <a href="{% my_url company_page_obj.previous_page_number 'page' request.GET.urlencode %}">&laquo; Previous  </a>
            {% endif %}

                <span class="current font-weight-bold">
                    Page {{ company_page_obj.number  }} of {{ company_page_obj.paginator.num_pages }}.
                </span>

            {% if company_page_obj.has_next %}
                <a href="{% my_url company_page_obj.next_page_number 'page' request.GET.urlencode %}">&raquo; Next</a>
                <a href="{% my_url company_page_obj.paginator.num_pages 'page' request.GET.urlencode %}"> &raquo; Last</a>
            {% endif %}
        </span>
    </div>
<hr>

{% endblock %}